# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins:             [jekyll-paginate]

# Setup
title:               ochre.red
tagline:             'pigments → pixels'
description:         'Made by <a href="https://twitter.com/ochre_red" target="_blank">@ochre_red</a>.'
url:                 http://ochre.red
baseurl:             ''
paginate:            5
tintcolor:          "#9A2F00"

# About/contact
author:
  name:              Satyakam Khadilkar
  url:               https://twitter.com/ochre_red
  email:             red@ochre.red

# Custom vars
version:             1.0.0
